# Generated by Django 4.1.4 on 2023-01-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vac', '0005_alter_skill_options_alter_vacancy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
